// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CarCRUD.Data; // Corrigido para CarCRUD.Data

#nullable disable

namespace CarCRUD.Migrations // Corrigido para CarCRUD.Migrations
{
    [DbContext(typeof(ContextoCarro))] // Corrigido para ContextoCarro
    partial class Inicial // Certifique-se de que o nome da classe corresponde ao nome da migração
    {
        /// <inheritdoc />
        protected void BuildModel(ModelBuilder modelBuilder) // Método correto: BuildModel
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CarCRUD.Models.CarroModelo", b => // Corrigido para CarroModelo
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Modelo") // Corrigido para Modelo
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Carros"); // Corrigido para Carros
            });
#pragma warning restore 612, 618
        }
    }
}